name: Build and Deploy

on:
  push:
    branches:
      - master
    paths:
      - packages/core/**
      - .github/workflows/core.yml
  pull_request:
    branches:
      - develop
      - master
    paths:
      - packages/core/**
      - .github/workflows/core.yml
  workflow_dispatch: # allow manual trigger
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '10.9.0'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm core:build

      - name: Bump patch version
        if: github.ref_name == 'master' && github.event_name == 'push'
        run: pnpm core:bump-patch-version
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: actions@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: actions@github.com

      - name: Authenticate with NPM
        if: github.ref_name == 'master' && github.event_name == 'push'
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Publish
        if: github.ref_name == 'master' && github.event_name == 'push'
        run: pnpm core:npm-publish

      - name: Commit bumped version
        if: github.ref_name == 'master' && github.event_name == 'push'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add packages/core/package.json # adjust if your bump affects more files
          VERSION=$(node -p "require('./packages/core/package.json').version")
          git commit -m "chore: bump version to v$VERSION [skip ci]"
          git tag v$VERSION

      - name: Push changes and tag
        if: github.ref_name == 'master' && github.event_name == 'push'
        run: |
          git push origin HEAD
          git push origin --tags
